# Generated by Django 5.1.1 on 2024-09-25 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='text',
            field=models.TextField(default='default question text'),
        ),
        migrations.AlterField(
            model_name='question',
            name='correct_answer',
            field=models.TextField(),
        ),
    ]
