# Generated by Django 5.1.1 on 2024-10-08 07:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0004_rename_correct_answer_question_correct_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cards', to='quiz.question'),
        ),
    ]
